### ISSUE TITLE
Пропозиція

### ISSUE THREAD

**Issue by mazahell** [vga1/learn-javascript#1]
- Папку таск перенести в issues (вони не треба в репозиторії)
- папку `code` перенести в корінь репозиторія, не треба тут ці лишні папки

**Comment by mazahell** [comment]
![selection_057](https://user-images.githubusercontent.com/5244650/42563736-a22c8ff8-8507-11e8-9323-8d0791294515.png)

**Comment by vga1** [comment]
done

**Comment by mazahell** [comment]
запуш зміни, а потім закриєш :)

**Comment by mazahell** [comment]
папка learn-javascript не треба

**Comment by vga1** [comment]
o зараз

**Comment by mazahell** [comment]
Уже добре, асле є одне але:

**Comment by vga1** [comment]
зробив
